M48
; DRILL file {KiCad 7.0.5-0} date 2023 June 25, Sunday 22:51:37
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-25T22:51:37+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X48.26Y-30.48
X48.26Y-88.9
X223.52Y-30.48
X223.52Y-88.9
T0
M30
